### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by carlsummer** [Megvii-BaseDetection/DynamicRouting#27]
Traceback (most recent call last):
  File "/home/carl-hui/workspace/pycharm-workspace/tianchi-logic-object/DynamicRouting/tools/train_net.py", line 23, in <module>
    import torch
  File "/home/carl-hui/software/env/tianchi/lib/python3.7/site-packages/torch/__init__.py", line 26, in <module>
    from typing import Set, Type
  File "/home/carl-hui/software/env/tianchi/lib/python3.7/site-packages/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/carl-hui/software/env/tianchi/lib/python3.7/site-packages/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/107045326-59c05e00-6800-11eb-8162-70583d2e2fb9.png)

**Comment by carlsummer** [comment]
i solved it
![Uploading image.png…]()
